version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: pollstation-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: pollstationDB
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    